#!/usr/bin/env python3.3 !!

# import package

from tkinter import *
from tkinter.messagebox import *
import tkinter as tk
import tkinter.tix
import tkinter.ttk
import tkinter.messagebox
import tkinter.colorchooser
import tkinter.filedialog
import tkinter.commondialog
import tkinter.simpledialog
import tkinter.font
import tkinter.dnd
import tkinter.scrolledtext

fenetre = Tk()

#label = Label(fenetre , text="Hi world")
#label.pack()


# Close button
#	BtClose = Button(fenetre, text="Close", command = fenetre.quit)
#	BtClose.pack()

#	# Input modul
#	OpInputVar = StringVar()
#	OpInputVar.set("Default operator input")
#	OpInputWdw = Entry(fenetre, textvariable = OpInputVar, width=30)
#	OpInputWdw.pack()

#	#Label
#	LbDefaultTxt = Label(fenetre, text="Coucou", bg='Yellow')
#	LbDefaultTxt.pack()

#	# canvas
#	canvas = Canvas(fenetre, width=150, height=120, background='yellow')
#	ligne1 = canvas.create_line(75, 0, 75, 120)
#	ligne2 = canvas.create_line(0, 60, 150, 60)
#	txt = canvas.create_text(75, 60, text="Cible", font="Arial 16 italic", fill="blue")
#	canvas.pack()
#	 
#	# Create a spinbox
#	s = Spinbox(fenetre, from_=0, to=10)
#	s.pack()


#	# Create a scale
#	value = DoubleVar()
#	scale = Scale(fenetre, variable=value)
#	scale.pack()

#	def callback():
#	    if askyesno('Titre 1', 'Êtes-vous sûr de vouloir faire ça?'):
#	        showwarning('Titre 2', 'Tant pis...')
#	    else:
#	        showinfo('Titre 3', 'Vous avez peur!')
#	        showerror("Titre 4", "Aha")

#	Button(text='Action', command=callback).pack()

Canvas(fenetre, width=250, height=100, bg='ivory').pack(side=TOP, padx=5, pady=5)
Button(fenetre, text ='Bouton 1').pack(side=LEFT, padx=5, pady=5)
Button(fenetre, text ='Bouton 2').pack(side=RIGHT, padx=5, pady=5)

Button(fenetre, text ="arrow", relief=RAISED, cursor="arrow").pack()
Button(fenetre, text ="circle", relief=RAISED, cursor="circle").pack()
Button(fenetre, text ="clock", relief=RAISED, cursor="clock").pack()
Button(fenetre, text ="cross", relief=RAISED, cursor="cross").pack()
Button(fenetre, text ="dotbox", relief=RAISED, cursor="dotbox").pack()
Button(fenetre, text ="exchange", relief=RAISED, cursor="exchange").pack()
Button(fenetre, text ="fleur", relief=RAISED, cursor="fleur").pack()
Button(fenetre, text ="heart", relief=RAISED, cursor="heart").pack()
Button(fenetre, text ="man", relief=RAISED, cursor="man").pack()
Button(fenetre, text ="mouse", relief=RAISED, cursor="mouse").pack()
Button(fenetre, text ="pirate", relief=RAISED, cursor="pirate").pack()
Button(fenetre, text ="plus", relief=RAISED, cursor="plus").pack()
Button(fenetre, text ="shuttle", relief=RAISED, cursor="shuttle").pack()
Button(fenetre, text ="sizing", relief=RAISED, cursor="sizing").pack()
Button(fenetre, text ="spider", relief=RAISED, cursor="spider").pack()
Button(fenetre, text ="spraycan", relief=RAISED, cursor="spraycan").pack()
Button(fenetre, text ="star", relief=RAISED, cursor="star").pack()
Button(fenetre, text ="target", relief=RAISED, cursor="target").pack()
Button(fenetre, text ="tcross", relief=RAISED, cursor="tcross").pack()
Button(fenetre, text ="trek", relief=RAISED, cursor="trek").pack()
Button(fenetre, text ="watch", relief=RAISED, cursor="watch").pack()


def alert():
    showinfo("alerte", "Bravo!")

menubar = Menu(fenetre)

menu1 = Menu(menubar, tearoff=0)
menu1.add_command(label="Créer", command=alert)
menu1.add_command(label="Editer", command=alert)
menu1.add_separator()
menu1.add_command(label="Quitter", command=fenetre.quit)
menubar.add_cascade(label="Fichier", menu=menu1)

menu2 = Menu(menubar, tearoff=0)
menu2.add_command(label="Couper", command=alert)
menu2.add_command(label="Copier", command=alert)
menu2.add_command(label="Coller", command=alert)
menubar.add_cascade(label="Editer", menu=menu2)

menu3 = Menu(menubar, tearoff=0)
menu3.add_command(label="A propos", command=alert)
menubar.add_cascade(label="Aide", menu=menu3)

fenetre.config(menu=menubar)

# run the window
fenetre.mainloop()